set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
set +o ignoreeof
set -o interactive-comments
set +o keyword
set +o monitor
set +o noclobber
set +o noexec
set +o noglob
set +o nolog
set +o notify
set +o onecmd
set +o physical
set -o pipefail
set +o posix
set +o privileged
set +o verbose
set +o vi
set +o xtrace
